#include <stdint.h>
#define MEMORYMAP_EXTRAM_BASE (0)
#define MEMORYMAP_UART_BASE (12582912)
#define MEMORYMAP_SYSTEMREGISTERS_BASE (13631488)
#define MEMORYMAP_BOOTROM_BASE
#define MEMORYMAP_BOOTRAM_BASE
